"make bookdiff" changes in the Norwegian book.
* src/nb/Makefile
  (bookdiff): If the $(BDTMP) directory exists, it can be removed by 
  pressing Enter. Also straighten up the output by hiding things.


git-svn-id: http://svnbook.googlecode.com/svn/trunk@1919 931749d0-5854-0410-9456-f14be4d6b398

diff --git a/src/nb/Makefile b/src/nb/Makefile
--- a/src/nb/Makefile
+++ b/src/nb/Makefile
@@ -57,10 +57,15 @@ convfiles:
 	done
 
 bookdiff:
-	mkdir $(BDTMP)
+	@mkdir $(BDTMP) || { \
+		echo -n "\"$(BDTMP)\" already exists. Press ENTER to delete it, or CTRL-C to abort..." >&2; \
+		read; \
+		rm -rf $(BDTMP); \
+		mkdir $(BDTMP); \
+	}
 	$(MAKE) engdir
 	cp -a book/eng $(BDTMP)/
-	for _ptd in $(BDFILES); do \
+	@for _ptd in $(BDFILES); do \
 		cat $(BDTMP)/eng/$$_ptd | bin/clean_files -e >>$(BDTMP)/eng.txt; \
 		cat book/$$_ptd | bin/clean_files -e >>$(BDTMP)/norw.txt; \
 	done
